### ISSUE TITLE
Acquire neuron models from the Allen Cell Types Database

### ISSUE THREAD

**Issue by eroma2014** [GT-ARTISAN/Cerebrum#19]
Allen Cell types database is https://celltypes.brain-map.org/data 
The current task will focus on four neuron types: 3 inhibitory ( SSt, PValb, ViP), 1 excitatory ( Scnn1a). 

### Tasks
- [x] Create a python module to query the Cell Types database using Allen SDK
- [x] Functionality to filter cell types, models and model properties
- [ ] Create a template for the complete workflow from acquisition to build-network
- [ ] Save the query description and its parameters 
    - [ ] Ability to modify the query description and/or parameters and re-run the workflow

Git repo: https://github.com/srirampc/airavata-cerebrum/tree/main/airavata_cerebrum
