### ISSUE TITLE
Acquire the neuron population ratios from brain single cell atlases

### ISSUE THREAD

**Issue by eroma2014** [GT-ARTISAN/Cerebrum#20]
Map the neuron types between the cell types of BICN.  We focus on the datbase : https://alleninstitute.github.io/abc_atlas_access/intro.html and the four cell types : SSt, Pvalb, Vip, and one of excitatory type

### Tasks

- [x] Obtain Cell type ratios from BICN Al merfish atlas
- [x] Filter based on the layer and neuron types
- [ ] Save the query description that enables modification and re-runs

Git repo: https://github.com/srirampc/airavata-cerebrum/tree/main/airavata_cerebrum
