### ISSUE TITLE
Acquire the synaptic probabilities from synaptic physiology database

### ISSUE THREAD

**Issue by eroma2014** [GT-ARTISAN/Cerebrum#21]
Synaptic physiology database : https://portal.brain-map.org/explore/connectivity/synaptic-physiology/synaptic-physiology-experiment-methods 

### Tasks

- [ ] Use aisynphys library to acquire data
- [ ] Filter based on the interaction neuron types
- [ ] Save the query description that enables modification and re-runs

Git repo: https://github.com/srirampc/airavata-cerebrum/tree/main/airavata_cerebrum
